### PR TITLE
fix: revert empty or faulty ssl certificates by regeneration

### LINKED ISSUE #224: BMC daemon fails to start - Empty SSL Certificate Files
Hi!

I just received my TuringPi today, and while setting everything up, I must have been too eager to remove power from the board. This caused what I identified as a state that required manual recovery.

The issue I encountered was related to the BMC’s certificate files. Specifically, I found that the `bmcd_cert.pem` file was 0 bytes in size after the system restarted. This prevented the BMC daemon and web interface from starting correctly and caused API commands such as `tpi power on` to fail.

Upon reviewing the BMC startup script, I noticed that the logic only checks for the existence of the .pem files but does not verify that the files are valid or non-empty.

Suggested Fix:

It would be ideal to improve the script by also checking that the certificate and key files are non-empty (i.e., contain valid data), using the -s flag instead of just -f. This ensures that the BMC can properly recover from situations where certificates are truncated to 0 bytes.

For example, this line:

https://github.com/turing-machines/BMC-Firmware/blob/0cd2260c80be4bf36b8126722f8a6a0bca13c0cf/tp2bmc/board/tp2bmc/factory_overlay/upper/etc/init.d/S94bmcd#L12

Could be changed to:

```bash
if [ ! -s "$CERTFILE" ] || [ ! -s "$KEYFILE" ]; then
    /etc/bmcd/generate_self_signedx509.sh
fi
```

This modification would ensure that the certificate files are checked not only for existence but also for being non-empty, helping to avoid issues like the one I encountered.

You could, of course, also do some of this validation in the bmcd project and just delete the certificates if they are not valid—whichever you find appropriate. I still don’t have a complete overview of the project in its entirety, so bear with me.

Thanks for your help, and I’m looking forward to getting everything up and running smoothly!

### PR DESCRIPTION
**Pull request by gjrtimmer**
fixes #224

This PR updates the generate certificate script as outlined in issue #224

### CODE REVIEW

File: tp2bmc/package/bmcd/generate_self_signedx509.sh [hunk 1]
```diff
@@ -1,10 +1,48 @@
...
+    echo "Generating new self-signed X509 certs.."
+    mkdir -p $ssl_dir
+    openssl req -x509 -newkey rsa:4096 -keyout $key_file \
+        -out $cert_file -nodes -subj "/CN=Turing-Pi self signed"
+    echo "Done"
+}
 
-echo "Done"
+# Check if cert and key exist
+if [ -f "$cert_file" ] && [ -f "$key_file" ]; then
```
Comment (svenrademakers) [inline tp2bmc/package/bmcd/generate_self_signedx509.sh:21]: This logic can be simplified. -s already checks if file exists.

I would expect something like:

If files are empty or validation fails {
delete files and generate_certs
}

File: tp2bmc/package/bmcd/generate_self_signedx509.sh [hunk 2]
```diff
@@ -1,10 +1,48 @@
 #!/bin/sh
+# shellcheck shell=sh
 
-echo "generating new self signed X509 certs.."
+ssl_dir=/mnt/c/Users/gert-jan.timmer/Projects/wip/ssl
```
Comment (svenrademakers) [inline tp2bmc/package/bmcd/generate_self_signedx509.sh:4]: Thats a strange dir :)

**Review by svenrademakers — CHANGES_REQUESTED** [review]

File: tp2bmc/package/bmcd/generate_self_signedx509.sh (hunk 2 above)
Comment (gjrtimmer) [reply tp2bmc/package/bmcd/generate_self_signedx509.sh:4]: Oeps, that was my test dir on my WIndows machine

File: tp2bmc/package/bmcd/generate_self_signedx509.sh (hunk 1 above)
Comment (gjrtimmer) [reply tp2bmc/package/bmcd/generate_self_signedx509.sh]: DONE

**Comment by gjrtimmer** [comment]
Changes DONE, Request Review

**Review by gjrtimmer — COMMENTED** [review]
Completed
